configuration_default = {
    'SYS_VEHICLE_RESP': -0.4,
    'MPC_ACC_HOR': 3,
    'MPC_ACC_HOR_MAX': 5,
    'MPC_TILTMAX_AIR': 45,
    'MPC_ACC_DOWN_MAX': 3,
    'MPC_ACC_UP_MAX': 4,
    'MPC_JERK_MAX': 8,
    'MPC_JERK_AUTO': 4,
    'MPC_XY_VEL_ALL': -10,
    'MPC_XY_CRUISE': 5,
    'MPC_XY_VEL_MAX': 12,
    'MPC_Z_VEL_ALL': -3,
    'MPC_Z_V_AUTO_UP': 3,
    'MPC_Z_VEL_MAX_UP': 3,
    'MPC_Z_V_AUTO_DN': 1.5,
    'MPC_Z_VEL_MAX_DN': 1.5,
    'MPC_TKO_SPEED': 1.5,
    'MPC_LAND_SPEED': 0.7,
    'MPC_TILTMAX_LND': 12,
    'MPC_THR_HOVER':0.5,
    'MPC_THR_MAX': 1,
    'MPC_THR_MIN': 0.12,
    'MC_PITCHRATE_MAX': 220,
    'MIS_YAW_ERR': 12,
    'MPC_YAWRAUTO_MAX': 45
}